courseTIM/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('particpants/', include('particpants.urls')),
    path('admin/', admin.site.urls)
]

particpants/urls.py
from django.urls import path

from . import views

# ne pas oublier le namespace
app_name = 'particpants'
urlpatterns = [
    path('', views.index, name='index'),
    path('listeparticipant', views.liste_participants, name='liste_participants'),
    path('listeparticipant/<int:participant_id>', views.detail_participant, name='detail_participant'),
    path('listecategories', views.liste_categories, name='liste_categories'),
    path('inscription', views.participant_create, name='inscription')
]

particpants/models.py
from django.db import models
from django.core import validators
from django.forms import RegexField


class Categorie(models.Model):
    nom_categorie = models.CharField(max_length=200)
    description_categorie = models.CharField(max_length=600)

    def __str__(self):
        return self.nom_categorie


# *** relation Many to many défini seulement dans la classe Participant,
# puisque rien ne sera ajouté à la table d'intersection
class Participant(models.Model):
    nom_participant = models.CharField(max_length=200)
    prenom_participant = models.CharField(max_length=200)
    courriel_participant = models.EmailField(max_length=300)
    date_naissance = models.DateField()
    actif = models.BooleanField('est présentement actif', default=True)
    categories = models.ManyToManyField(Categorie)

    #regex
    # regex = RegexField

    def __str__(self):
        return self.prenom_participant + " " + self.nom_participant

    def nom_complet(self):
        return self.prenom_participant + " " + self.nom_participant

particpants/forms.py
# from django import forms
from django.core import validators
from django.core.validators import RegexValidator
from django import forms
from .models import Participant, Categorie


class InscriptionParticipantForm(forms.ModelForm):
    class Meta:
        prenom_participant = forms.CharField()
        model = Participant
        fields = [
            'prenom_participant',
            'nom_participant',
            'courriel_participant',
            'date_naissance',
            'categories'
        ]
        labels = {
            'prenom_participant': 'Votre prénom',
            'nom_participant': 'Votre nom',
            'courriel_participant': 'Votre courriel',
            'date_naissance': 'Votre date de naissance',
            'categories': 'Le ou les catégories dans lesquelles vous vous inscrivez'
        }
        error_messages = {
            'prenom_participant': {
                'max_length': "Votre prénom dépasse le nombre de caractères permis.",
            },
        }

    def clean_prenom_participant(self):
        regex_noms = RegexValidator('^[A-zÀ-ÿ -\']$', "Votre prénom ne doit contenir que des lettres, des traits d'union, des apostrophes ou des espaces.")
        prenom_participant = self.cleaned_data.get("prenom_participant")
        regex_noms('prenom_participant')


# class InscriptionForm(ModelForm):
#     class Meta:
#         model = Categorie.participants.through
#         fields = [
#             'nom_categorie',
#             'participants'
#         ]
#         widgets = {}


# class RegexValidator:
#     regex = '',
#     message = '',
#     code = '',
#     inverse_match = False,
#     flags = 0,
#
#     def __init__(self, regex=None, message=None, code=None, inverse_match=None, flags=None):
#         if regex is not None:
#             self.regex = regex
#         if message is not None:
#             self.message = message
#         if code is not None:
#             self.code = code
#         if inverse_match is not None:
#             self.inverse_match = inverse_match
#         if flags is not None:
#             self.flags = flags
#
#     def __call__(self, value):

particpants/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404

from .models import Participant, Categorie
from .forms import InscriptionParticipantForm


# Create your views here.
def index(request):

    return render(request, 'particpants/index.html')


def liste_participants(request):
    participants_course = Participant.objects.order_by('nom_participant')
    context = {
        'participants_course': participants_course
    }
    return render(request, 'particpants/listeparticipants.html', context)


def detail_participant(request, participant_id):
    participant = get_object_or_404(Participant, pk=participant_id)
    context = {
        'participant': participant
    }
    return render(request, 'particpants/detailparticipant.html', context)


def liste_categories(request):
    toutes_categories = Categorie.objects.order_by('nom_categorie')
    context = {
        'toutes_categories': toutes_categories,
        'participants': Participant.objects.all
    }
    return render(request, 'particpants/listecategories.html', context)


def participant_create(request):
    validation_ok = False
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = InscriptionParticipantForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            validation_ok = True
            form.save()
    else:
        form = InscriptionParticipantForm

    context = {
        'form': form,
        'formValidate': validation_ok
    }
    return render(request, 'particpants/inscription.html', context)

particpants/templates/particpants/detailparticipant.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title>Détails du participant</title>
</head>
<body>
    <h1>Détails du participant {{ participant.prenom_participant }} {{ participant.nom_participant }}</h1>

    <p>Prénom : {{ participant.prenom_participant }}</p>
    <p>Nom : {{ participant.nom_participant }}</p>
    <p>Catégories dans lesquelles le participant se trouve :</p>
    <ul>
        {% for categorie in participant.categories.all %}
            <li>{{ categorie.nom_categorie }}</li>
        {% endfor %}
    </ul>
<p><a href="{% url 'particpants:liste_participants' %}">Retour à la liste des participants</a></p>
</body>
</html>

particpants/templates/particpants/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Accueil de la course TIM</title>
</head>
<body>
    <h1>COURSE TIM</h1>
    <h2>Bienvenue sur la page de la course TIM!</h2>
    <p><a href="{% url 'particpants:liste_participants' %}">Consulter la liste des participants</a></p>
    <p><a href="{% url 'particpants:liste_categories' %}">Consulter la liste des catégories</a></p>
    <p><a href="{% url 'admin:index' %}">Je suis administrateur</a></p>
</body>
</html>

particpants/templates/particpants/inscription.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Formulaire d'inscription</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'particpants/styles.css' %}">
</head>
<body>
    <h1>Inscription à la course TIM</h1>
    {% if formValidate == False %}
        <form action="#" method="post">
            {% csrf_token %}
            {# .as_p met les groupes label et input dans des balises p #}
            {{ form.as_p }}
            <button>M'inscrire</button>
        </form>
    {% else %}
        <p>Vous êtes bien inscrit à la course TIM!</p>
    {% endif %}
    <p><a href="{% url 'particpants:index' %}">Retour à l'accueil</a></p>
</body>
</html>

particpants/templates/particpants/listecategories.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Liste des catégories</title>
{#    {% load static %}#}
{#    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">#}
</head>
<body>
    <h1>Liste des catégories de la course TIM</h1>
    {% if toutes_categories %}
        {% for categorie in toutes_categories %}
            <div>
                <h2>{{ categorie.nom_categorie }}</h2>
                <p>Distance : {{ categorie.description_categorie }}</p>
                {% if participants %}
                    <p>Participants : </p>
                    <ul>
                        {% for participant in participants %}
                            {% for categorie_participant in participant.categories.all %}
                                {% if categorie.id == categorie_participant.id %}
                                    <li>
                                        <a href="{% url 'particpants:detail_participant' participant.id %}">{{ participant.prenom_participant }} {{ participant.nom_participant }}</a>
                                    </li>
                                {% endif %}
                            {% endfor %}
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
        {% endfor %}
    {% else %}
        <li>Il n'y a pas encore de catégorie à la course TIM!</li>
    {% endif %}

    <p><a href="{% url 'particpants:inscription' %}">Je veux m'inscrire!</a></p>
    <p><a href="{% url 'particpants:index' %}">Retour à l'accueil</a></p>
</body>
</html>

particpants/templates/particpants/listeparticipants.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Liste des participants</title>
{#    {% load static %}#}
{#    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">#}
</head>
<body>
    <h1>Liste des participants à la course TIM</h1>
    <h2>Sélectionnez un des participants pour avoir plus d'informations</h2>
    {% if participants_course %}
        <ul>
        {% for participant in participants_course %}
            <li><a href="{% url 'particpants:detail_participant' participant.id %}">{{ participant.prenom_participant }} {{ participant.nom_participant }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>Il n'y a pas encore de participants à la course!</p>
    {% endif %}

    <p><a href="{% url 'particpants:inscription' %}">Je veux m'inscrire!</a></p>
    <p><a href="{% url 'particpants:index' %}">Retour à l'accueil</a></p>
</body>
</html>